version: '3'

services:
  # Frontend React application
  fleet-frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://fleet-backend:5000/api
    depends_on:
      - fleet-backend
    restart: unless-stopped

  # Backend API service (placeholder - to be implemented)
  fleet-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://fleet-db:27017/fleet
    depends_on:
      - fleet-db
    restart: unless-stopped

  # MongoDB database
  fleet-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
