version: '3'

services:
  # Frontend React application
  fleet-frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3020:3000"
    volumes:
      - ./react-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://fleet-backend:5000/api
    depends_on:
      - fleet-backend
    restart: unless-stopped

  # Backend API service (placeholder - to be implemented)
  fleet-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@fleet-db:5432/fleet
    depends_on:
      - fleet-db
    restart: unless-stopped

  # PostgreSQL database
  fleet-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fleet
    restart: unless-stopped

volumes:
  postgres_data:
