version: '3'

services:
  # Frontend React application
  fleet-frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3020:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_TITLE=${REACT_APP_TITLE}
      - REACT_APP_VERSION=${REACT_APP_VERSION}
    depends_on:
      - fleet-backend
    restart: unless-stopped

  # Backend API service (placeholder - to be implemented)
  fleet-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT:-5000}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@fleet-db:5432/${POSTGRES_DB}
    depends_on:
      - fleet-db
    restart: unless-stopped

  # PostgreSQL database
  fleet-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

volumes:
  postgres_data:
