version: '3.8'

services:
  # Frontend React App
  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: fleet-frontend
    restart: always
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - fleet-network

networks:
  fleet-network:
    driver: bridge
